name: Lighthouse Audit

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install and set up a simple HTTP server
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install serve
        run: npm install -g serve
      
      # Run Lighthouse CI with explicit server command
      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            http://localhost:8080/
          serverBaseDir: '.'
          serverCommand: 'serve -p 8080'
          uploadArtifacts: true
          temporaryPublicStorage: true
      
      - name: Check performance score
        if: ${{ always() }}
        run: |
          echo "Lighthouse audit completed. Results are available in the GitHub Actions artifacts."
          echo "If GitHub Pages is enabled, the site will be audited at the URL above." 