name: Lighthouse Audit

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://balavinayagapragathishsathish.github.io/lighthouse-performance-metrics/
          uploadArtifacts: true
          temporaryPublicStorage: true
      
      - name: Check performance score
        if: ${{ always() }}
        run: |
          echo "Lighthouse audit completed. Results are available in the GitHub Actions artifacts."
          echo "If GitHub Pages is enabled, the site will be audited at the URL above." 