name: Lighthouse Audit

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up a simple HTTP server to serve the static files
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install http-server
        run: npm install -g http-server
      
      - name: Start HTTP server
        run: |
          http-server . -p 8080 &
          sleep 5  # Give the server time to start
      
      # Run Lighthouse CI against the local server
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            http://localhost:8080/
            http://localhost:8080/index.html
          uploadArtifacts: true
          temporaryPublicStorage: true
      
      - name: Check performance score
        if: ${{ always() }}
        run: |
          echo "Lighthouse audit completed. Results are available in the GitHub Actions artifacts."
          echo "If GitHub Pages is enabled, the site will be audited at the URL above." 